AdobeDocs/document-services

- gatsby-browser.js
- gatsby-config.js
- src/pages/apis/doc-generation.md
- src/pages/apis/doc-generation/dg-start-modifying-pdf.md
- src/pages/apis/pdf-embed.md
- src/pages/apis/pdf-embed/key-features.md
- src/pages/apis/pdf-embed/start-embedding.md
- src/pages/apis/pdf-embed/why-pdf-embed.md
- src/pages/apis/pdf-extract.md
- src/pages/apis/pdf-extract/extract-stepper.md
- src/pages/apis/pdf-extract/why-extract-api.md
- src/pages/apis/pdf-services.md
- src/pages/apis/pdf-services/key-features-code-block.md
- src/pages/apis/pdf-services/start-modifying-pdf.md
- src/pages/index.md
- src/pages/pricing/pdf-embed-api.md
> URL update for new onboarding application

- src/pages/apis/doc-generation.md
- src/pages/apis/doc-generation/dg-start-modifying-pdf.md
- src/pages/apis/pdf-embed.md
- src/pages/apis/pdf-embed/key-features.md
- src/pages/apis/pdf-embed/start-embedding.md
- src/pages/apis/pdf-embed/why-pdf-embed.md
- src/pages/apis/pdf-extract.md
- src/pages/apis/pdf-extract/extract-stepper.md
- src/pages/apis/pdf-extract/why-extract-api.md
- src/pages/apis/pdf-services.md
- src/pages/apis/pdf-services/extract-pdf-content.md
- src/pages/apis/pdf-services/key-features-code-block.md
- src/pages/apis/pdf-services/start-modifying-pdf.md
- src/pages/home/pdf-content-structure.md
- src/pages/index.md
- src/pages/pricing/pdf-embed-api.md
> Fix URL for rest apis

- src/pages/apis/pdf-extract.md
- src/pages/apis/pdf-extract/extract-stepper.md
- src/pages/apis/pdf-extract/visualizer-how-it-works.md
- src/pages/apis/pdf-extract/why-extract-api.md
> Added the missed usecase blade on pdf extract screen

- gatsby-browser.js
- src/pages/apis/microsoft-PA-integration/ms-announcement.md
- src/pages/apis/microsoft-pa-integration.md
Added the Announcement blade on microsoft screen
All kind of Unit test
> Feature 144 announce

- gatsby-browser.js
- src/pages/pricing/contact/sales/confirmation.md
- src/pages/pricing/contact/sales/index.md
- src/pages/pricing/contact/sales/sale-confirmation-content.md
- src/pages/pricing/contact/support/confirmation.md
- src/pages/pricing/contact/support/index.md
- src/pages/pricing/contact/support/support-confirmation-content.md
- src/styles/main.css
Updated the CTA links for confirmation pages
Fixed few alignment and also responsive issues
content horizontal align issue fix
> CUF confirmation changes

- gatsby-browser.js
- src/pages/apis/doc-gen-api-template.md
- src/pages/apis/pdf-services/use-cases-resource-cards.md
> Fixed the doc-gen-api-template and PDF services page capitalize issue

- gatsby-config.js
> updated the top nav with contact us menu

- gatsby-browser.js
- src/pages/pricing/contact/sales/sale-confirmation-content.md
> Fixed start free trial CTA url issue

- src/pages/pricing/contacts/accessibility-left.md
> Added the accessibility changes

- src/pages/pricing/contacts/accessibility-left.md
> Updated the left side content

- gatsby-browser.js
- src/components/retargetting.js
- src/components/salesContactUs.js
- src/components/tech-supportContactUs.js
- src/pages/pricing/contact/sales/confirmation.md
- src/pages/pricing/contact/sales/sale-confirmation-content.md
- src/pages/pricing/contact/support/confirmation.md
- src/pages/pricing/contact/support/support-confirmation-content.md
- src/styles/main.css
> Feature 158

- src/components/salesContactUs.js
- src/components/tech-supportContactUs.js
> Fixed the redirect url issue

- gatsby-browser.js
- src/components/formComponent/CheckBoxField.js
- src/components/formComponent/InputField.js
- src/components/pdfAccessibility.js
- src/components/salesContactUs.js
- src/pages/pricing/contact/sales/accessibility-content.md
- src/pages/pricing/contact/sales/accessibility.md
- src/styles/main.css
> Feature 161

- gatsby-config.js
- src/pages/apis/doc-gen-api-template.md
- src/pages/apis/doc-generation.md
- src/pages/apis/microsoft-PA-integration/left-content.md
- src/pages/apis/microsoft-PA-integration/right-content.md
- src/pages/apis/pdf-embed.md
- src/pages/apis/pdf-extract.md
- src/pages/apis/pdf-services.md
- src/pages/index.md
- src/pages/resources/index.md
- src/pages/resources/summary.md
Added the contact us URl on the resources menu
> Updated contact us CTA URLs

- src/pages/pricing/main.md
> Updated the Contact us CTA URLs

- src/components/pdfAccessibility.js
- src/pages/pricing/index.md
> Updated the accessibility form content and pop up message

- src/components/pdfAccessibility.js
- src/components/salesContactUs.js
- src/components/tech-supportContactUs.js
> Updated the URL and Field label names

- src/components/pdfAccessibility.js
- src/components/salesContactUs.js
- src/components/tech-supportContactUs.js
- src/styles/main.css
> Added the loader for 3X CUF Forms

- gatsby-browser.js
- gatsby-config.js
- gatsby-ssr.js
- src/pages/apis/doc-generation.md
- src/pages/apis/doc-generation/dg-explore-other-adobe-doc.md
- src/pages/apis/doc-generation/dg-start-modifying-pdf.md
- src/pages/apis/pdf-embed.md
- src/pages/apis/pdf-embed/embed-modes.md
- src/pages/apis/pdf-embed/explore-adobe.md
- src/pages/apis/pdf-embed/key-features.md
- src/pages/apis/pdf-embed/menu-tool-options.md
- src/pages/apis/pdf-embed/start-embedding.md
- src/pages/apis/pdf-embed/why-pdf-embed.md
- src/pages/apis/pdf-extract.md
- src/pages/apis/pdf-extract/extract-product.md
- src/pages/apis/pdf-extract/extract-stepper.md
- src/pages/apis/pdf-extract/why-extract-api.md
- src/pages/apis/pdf-services.md
- src/pages/apis/pdf-services/document-services-product-cards.md
- src/pages/apis/pdf-services/key-features-code-block.md
- src/pages/apis/pdf-services/start-modifying-pdf.md
- src/pages/enterprise/Reimagine_your_document.md
- src/pages/enterprise/index.md
- src/pages/home/embed-pdf-viewing-analytics.md
- src/pages/index.md
- src/pages/pricing/contact/sales/sale-confirmation-content.md
- src/pages/pricing/pdf-embed-api.md
> Feature 166

- gatsby-browser.js
> Fixed the Start Trial Free CTA URl issue

- gatsby-browser.js
- src/pages/apis/doc-generation/dg-start-modifying-pdf.md
- src/pages/apis/pdf-extract/extract-stepper.md
- src/pages/apis/pdf-services/combine-pdf.md
- src/pages/apis/pdf-services/compress-pdf.md
- src/pages/apis/pdf-services/convert-pdf.md
- src/pages/apis/pdf-services/create-pdf.md
- src/pages/apis/pdf-services/delete-pdf-pages.md
- src/pages/apis/pdf-services/document-generation.md
- src/pages/apis/pdf-services/extract-pdf-content.md
- src/pages/apis/pdf-services/get-pdf-properties.md
- src/pages/apis/pdf-services/html-to-pdf.md
- src/pages/apis/pdf-services/insert-pdf-pages.md
- src/pages/apis/pdf-services/linearize-pdf.md
- src/pages/apis/pdf-services/ocr-pdf.md
- src/pages/apis/pdf-services/remove-pdf-password.md
- src/pages/apis/pdf-services/reorder-pdf-pages.md
- src/pages/apis/pdf-services/replace-pdf-pages.md
- src/pages/apis/pdf-services/rotate-pdf-pages.md
- src/pages/apis/pdf-services/secure-pdf.md
- src/pages/apis/pdf-services/split-pdf.md
- src/pages/home/create-pdf-from-url.md
- src/pages/home/dynamic-pdf-document-generation.md
- src/pages/home/pdf-content-structure.md
- src/pages/index.md
> Feature 169

- gatsby-browser.js
- gatsby-config.js
- src/pages/apis/pdf-services/start-modifying-pdf.md
> Updated the PDF-services URL and also TopNav

- gatsby-config.js
> Updated the Document top nav submenu

- src/components/tech-supportContactUs.js
- src/pages/pricing/pay-as-you-go.md
- src/styles/main.css
> Updated the spell issues and pricing page contents

- gatsby-config.js
> Added the API page on topnav

- src/pages/apis/doc-generation.md
- src/pages/apis/doc-generation/dg-explore-other-adobe-doc.md
- src/pages/apis/pdf-embed/explore-adobe.md
- src/pages/apis/pdf-extract.md
- src/pages/apis/pdf-extract/visualizer-how-it-works.md
- src/pages/apis/pdf-services/document-services-product-cards.md
- src/pages/index.md
> Updated the sub domain urls

- src/pages/apis/doc-generation.md
- src/pages/apis/pdf-embed.md
- src/pages/index.md
> Updated the doc-gen page sub domain URLs

- src/pages/apis/pdf-extract.md
- src/pages/pricing/pdf-embed-api.md
> Updated the subdomain URLs

- src/pages/pricing/contact/support/support-confirmation-content.md
- src/styles/main.css
> Fixed the typo issue and text alignment issues

- src/pages/apis/pdf-services/combine-pdf.md
- src/pages/apis/pdf-services/compress-pdf.md
- src/pages/apis/pdf-services/convert-pdf.md
- src/pages/apis/pdf-services/create-pdf.md
- src/pages/apis/pdf-services/delete-pdf-pages.md
- src/pages/apis/pdf-services/document-generation.md
- src/pages/apis/pdf-services/extract-pdf-content.md
- src/pages/apis/pdf-services/get-pdf-properties.md
- src/pages/apis/pdf-services/html-to-pdf.md
- src/pages/apis/pdf-services/insert-pdf-pages.md
- src/pages/apis/pdf-services/linearize-pdf.md
- src/pages/apis/pdf-services/ocr-pdf.md
- src/pages/apis/pdf-services/remove-pdf-password.md
- src/pages/apis/pdf-services/reorder-pdf-pages.md
- src/pages/apis/pdf-services/replace-pdf-pages.md
- src/pages/apis/pdf-services/rotate-pdf-pages.md
- src/pages/apis/pdf-services/secure-pdf.md
- src/pages/apis/pdf-services/split-pdf.md
- src/pages/home/create-pdf-from-url.md
- src/pages/home/dynamic-pdf-document-generation.md
- src/pages/home/pdf-content-structure.md
> update asset id

- src/pages/apis/doc-generation/dg-download-sample.md
- src/pages/apis/doc-generation/dg-start-modifying-pdf.md
- src/pages/apis/microsoft-pa-integration.md
- src/pages/apis/pdf-embed/menu-tool-options.md
- src/pages/apis/pdf-services/document-generation.md
> Updated the URLs as per JIRA

- src/styles/main.css
> Fixed the confirmation content align issue

- src/pages/apis/doc-generation/dg-start-modifying-pdf.md
> Updated the Doc gen URLs

- src/pages/apis/pdf-services/get-pdf-properties.md
> Updated the code block contents

- src/pages/apis/doc-generation/dg-explore-other-adobe-doc.md
- src/pages/apis/pdf-embed/explore-adobe.md
- src/pages/apis/pdf-extract.md
- src/pages/apis/pdf-extract/visualizer-how-it-works.md
- src/pages/apis/pdf-services/document-services-product-cards.md
- src/pages/index.md
> Updated the URLs

- gatsby-config.js
- src/@adobe/gatsby-theme-aio/components/Footer/index.js
> Updated the TobNav name and URLs

- src/pages/apis/pdf-services/get-pdf-properties.md
> Updated the codeblock content

- src/pages/apis/pdf-services/get-pdf-properties.md
> Fixed the sample code aligned issue

- .github/workflows/test-pull-request.yml
- gatsby-config.js
> Feature 177

- src/@adobe/gatsby-theme-aio/components/CustomMenuBlock/index.js
> Feature 176

- src/components/tech-support-dropdown-data.json
- src/components/tech-supportContactUs.js
- src/pages/faq/tech-support-content.md
> Added the new FAQ on tech-support FAQ page

- gatsby-browser.js
- src/components/electronicSealForm.js
- src/pages/pricing/contact/sales/seal/e-seal-api-content.md
- src/pages/pricing/contact/sales/seal/index.md
Fixed the Form alignment issue.
Updated the form content and fixed the alignment issue
> Designed the new form for E-seal-API

- src/components/electronicSealForm.js
- src/components/pdfAccessibility.js
- src/components/salesContactUs.js
- src/components/tech-supportContactUs.js
> Updated the all 4 x CUF's (Sales, TS, Seal, Accessibility) endpoint URL

- yarn.lock
> Fix build issue

- src/pages/apis/microsoft-PA-integration/ms-announcement.md
> Updated the PA page 'Register Now' CTA Url link

- src/@adobe/gatsby-theme-aio/components/AnchorButton/index.js
> Fixed the CTA urls change issue

- src/pages/apis/sign-api.md
- src/pages/apis/sign-api/partner-with-us.md
- src/styles/main.css
> Updated the CTA link and also embed the YT video

- src/@adobe/gatsby-theme-aio/components/WrapperComponent/index.js
- src/pages/apis/doc-generation.md
- src/pages/apis/doc-generation/dg-download-sample.md
> Feature 191

- src/components/electronicSealForm.js
- src/components/formComponent/RadioField.js
- src/styles/main.css
> Feature 192

- gatsby-browser.js
- src/pages/apis/microsoft-PA-integration/ms-announcement.md
> Updated the text on on Microsoft PA page

- src/components/tech-support-dropdown-data.json
- src/components/tech-supportContactUs.js
- src/pages/faq/tech-support-content.md
> Updated and added the new FAQ question and answer

- gatsby-browser.js
- gatsby-config.js
- src/pages/apis/doc-generation.md
- src/pages/apis/doc-generation/dg-start-modifying-pdf.md
- src/pages/apis/microsoft-pa-integration.md
- src/pages/apis/pdf-embed.md
- src/pages/apis/pdf-embed/key-features.md
- src/pages/apis/pdf-embed/start-embedding.md
- src/pages/apis/pdf-embed/why-pdf-embed.md
- src/pages/apis/pdf-extract.md
- src/pages/apis/pdf-extract/extract-stepper.md
- src/pages/apis/pdf-extract/why-extract-api.md
- src/pages/apis/pdf-services.md
- src/pages/apis/pdf-services/key-features-code-block.md
- src/pages/apis/pdf-services/start-modifying-pdf.md
- src/pages/enterprise/Reimagine_your_document.md
- src/pages/enterprise/index.md
- src/pages/index.md
- src/pages/pricing/contact/sales/sale-confirmation-content.md
- src/pages/pricing/pdf-embed-api.md
> Remove the Interstitial page and updated the URLs

- src/@adobe/gatsby-theme-aio/components/Accordion/index.js
- src/@adobe/gatsby-theme-aio/components/MDXFilter/MDXBlocks.js
- src/@adobe/gatsby-theme-aio/components/MDXFilter/MDXComponents.js
- src/@adobe/gatsby-theme-aio/components/MDXFilter/index.js
- src/pages/faq/sales-content.md
- src/styles/main.css
Added the FAQ question based navigation
Fixed the scroll overflow issue
> Added the FAQ page header text navigation

- src/pages/apis/pdf-extract.md
- src/pages/apis/pdf-services.md
- src/pages/apis/sign-api.md
- src/pages/index.md
> Removed the seal API blade on all the pages

- src/components/dynamicContentLoader.js
- src/pages/home/home-storyies.md
> Updated the home story blade titles on HP and Resources pages

- gatsby-browser.js
- gatsby-config.js
- src/pages/apis/accessibility-auto-tag-api/accessibility-adobe-doc.md
- src/pages/apis/accessibility-auto-tag-api/auto-tag-api-key-feature.md
- src/pages/apis/accessibility-auto-tag-api/benefits-of-accessibility-title.md
- src/pages/apis/accessibility-auto-tag-api/benefitsOfAccessibilityContent.md
- src/pages/apis/accessibility-auto-tag-api/industry-usecase.md
- src/pages/apis/accessibility-auto-tag-api/pdf-accessibility.md
- src/pages/apis/accessibility-auto-tag-api/technical-usecase.md
- src/pages/apis/pdf-accessibility-auto-tag.md
> Added the DCMKT-167 changes to 05/09 PTP

- src/pages/pricing/pay-as-you-go.md
- src/pages/pricing/volume-pricing.md
> Updated the pricing page content

- src/components/tech-support-dropdown-data.json
- src/components/tech-supportContactUs.js
- src/pages/apis/pdf-services/aws-ms-carousel.md
- src/pages/faq/sales-content.md
- src/pages/faq/tech-support-content.md
Removed the AWS related contents across the site
> Removed the AWS related links and contents across site

- gatsby-browser.js
- src/pages/pricing/pay-as-you-go.md
> Updated the start free trial CTA links

- src/components/dynamicContentLoader.js
> Updated the Tutorial Button link

- gatsby-browser.js
- src/pages/apis/microsoft-PA-integration/ms-announcement.md
> Updated the Microsoft-PA page contents

- src/components/dynamicContentLoader.js
> Added the "All Customer Stories" CTA on resources page

- src/pages/apis/accessibility-auto-tag-api/pdf-accessibility.md
> Corrected the accessibility-auto-tag-api page typo issue

- src/pages/apis/pdf-extract.md
- src/pages/apis/pdf-services.md
- src/pages/apis/sign-api.md
- src/pages/index.md
> Removed the Seal API contents

- gatsby-browser.js
- gatsby-config.js
- src/components/tech-support-dropdown-data.json
- src/pages/apis/doc-generation.md
- src/pages/apis/doc-generation/dg-start-modifying-pdf.md
- src/pages/apis/microsoft-PA-integration/getStarted.md
- src/pages/apis/microsoft-pa-integration.md
- src/pages/apis/pdf-accessibility-auto-tag.md
- src/pages/apis/pdf-extract.md
- src/pages/apis/pdf-extract/why-extract-api.md
- src/pages/apis/pdf-services.md
- src/pages/apis/pdf-services/key-features-code-block.md
- src/pages/enterprise/Reimagine_your_document.md
- src/pages/enterprise/index.md
- src/pages/faq/sales-content.md
- src/pages/faq/tech-support-content.md
- src/pages/index.md
- src/pages/pricing/contact/sales/sale-confirmation-content.md
- src/pages/pricing/index.md
- src/pages/pricing/main.md
- src/pages/pricing/pay-as-you-go.md
> Updated the text free tier instead of free trial

- src/pages/pricing/pay-as-you-go.md
> updated the pricing page.

- src/styles/main.css
> --Fixed alignment issue

- src/styles/main.css
> Added Dedicated Page for Customer Stories

- src/pages/pricing/volume-pricing.md
> Updated the content in pricing page

- src/styles/main.css
> Fixed design issue on the customer stories

- src/pages/apis/pdf-services/e-seal.md
- src/pages/apis/pdf-services/key-features-code-block.md
> Updated the code snippet for e-seal API in PDF service page

- src/pages/apis/sign-api.md
> Added seal API beta blades

- src/pages/apis/sign-api.md
> Updated the link to the API in Signapi page

- src/pages/apis/pdf-services/e-seal.md
- src/pages/index.md
- src/styles/main.css
> Feature june 215

- src/pages/apis/pdf-services/e-seal.md
- src/pages/home/e-seal.md
> Updated the e-seal API code snippet

- src/components/tech-support-dropdown-data.json
- src/components/tech-supportContactUs.js
- src/pages/faq/sales-content.md
- src/pages/faq/tech-support-content.md
> Updated the free tier word to Free Tier

- static/sales.html
- static/styles/styles.css
> Bug fix 235

- src/pages/apis/pdf-services/html-to-pdf.md
> Fixed the code snippet issue.

- src/pages/apis/pdf-services/accessibility-auto-tag-api.md
- src/pages/apis/pdf-services/combine-pdf.md
- src/pages/apis/pdf-services/compress-pdf.md
- src/pages/apis/pdf-services/convert-pdf.md
- src/pages/apis/pdf-services/create-pdf.md
- src/pages/apis/pdf-services/delete-pdf-pages.md
- src/pages/apis/pdf-services/document-generation.md
- src/pages/apis/pdf-services/e-seal.md
- src/pages/apis/pdf-services/extract-pdf-content.md
- src/pages/apis/pdf-services/get-pdf-properties.md
- src/pages/apis/pdf-services/html-to-pdf.md
- src/pages/apis/pdf-services/insert-pdf-pages.md
- src/pages/apis/pdf-services/linearize-pdf.md
- src/pages/apis/pdf-services/ocr-pdf.md
- src/pages/apis/pdf-services/remove-pdf-password.md
- src/pages/apis/pdf-services/reorder-pdf-pages.md
- src/pages/apis/pdf-services/replace-pdf-pages.md
- src/pages/apis/pdf-services/rotate-pdf-pages.md
- src/pages/apis/pdf-services/secure-pdf.md
- src/pages/apis/pdf-services/split-pdf.md
- src/pages/home/accessbility-auto-tag.md
- src/pages/home/dynamic-pdf-document-generation.md
- src/pages/home/e-seal.md
- src/pages/home/pdf-content-structure.md
> Updated the java sample code

- src/pages/apis/pdf-services/accessibility-auto-tag-api.md
- src/pages/apis/pdf-services/combine-pdf.md
- src/pages/apis/pdf-services/compress-pdf.md
- src/pages/apis/pdf-services/convert-pdf.md
- src/pages/apis/pdf-services/create-pdf.md
- src/pages/apis/pdf-services/delete-pdf-pages.md
- src/pages/apis/pdf-services/document-generation.md
- src/pages/apis/pdf-services/e-seal.md
- src/pages/apis/pdf-services/extract-pdf-content.md
- src/pages/apis/pdf-services/get-pdf-properties.md
- src/pages/apis/pdf-services/html-to-pdf.md
- src/pages/apis/pdf-services/insert-pdf-pages.md
- src/pages/apis/pdf-services/linearize-pdf.md
- src/pages/apis/pdf-services/ocr-pdf.md
- src/pages/apis/pdf-services/remove-pdf-password.md
- src/pages/apis/pdf-services/reorder-pdf-pages.md
- src/pages/apis/pdf-services/replace-pdf-pages.md
- src/pages/apis/pdf-services/rotate-pdf-pages.md
- src/pages/apis/pdf-services/secure-pdf.md
- src/pages/apis/pdf-services/split-pdf.md
- src/pages/home/accessbility-auto-tag.md
- src/pages/home/create-pdf-from-url.md
- src/pages/home/dynamic-pdf-document-generation.md
- src/pages/home/e-seal.md
- src/pages/home/pdf-content-structure.md
- Updated the Node JS samples on Home and PDF Services API pages.
> Update node samples

- src/pages/apis/pdf-services/accessibility-auto-tag-api.md
- src/pages/apis/pdf-services/combine-pdf.md
- src/pages/apis/pdf-services/compress-pdf.md
- src/pages/apis/pdf-services/convert-pdf.md
- src/pages/apis/pdf-services/create-pdf.md
- src/pages/apis/pdf-services/delete-pdf-pages.md
- src/pages/apis/pdf-services/document-generation.md
- src/pages/apis/pdf-services/e-seal.md
- src/pages/apis/pdf-services/extract-pdf-content.md
- src/pages/apis/pdf-services/get-pdf-properties.md
- src/pages/apis/pdf-services/html-to-pdf.md
- src/pages/apis/pdf-services/insert-pdf-pages.md
- src/pages/apis/pdf-services/linearize-pdf.md
- src/pages/apis/pdf-services/ocr-pdf.md
- src/pages/apis/pdf-services/remove-pdf-password.md
- src/pages/apis/pdf-services/reorder-pdf-pages.md
- src/pages/apis/pdf-services/replace-pdf-pages.md
- src/pages/apis/pdf-services/rotate-pdf-pages.md
- src/pages/apis/pdf-services/secure-pdf.md
- src/pages/apis/pdf-services/split-pdf.md
- src/pages/home/accessbility-auto-tag.md
- src/pages/home/create-pdf-from-url.md
- src/pages/home/dynamic-pdf-document-generation.md
- src/pages/home/e-seal.md
- src/pages/home/pdf-content-structure.md
Updated python code samples based on the sdk update.
> Updated the python sdk code samples

- src/pages/apis/accessibility-auto-tag-api/accessibility-stepper.md
- src/pages/apis/doc-generation/dg-start-modifying-pdf.md
- src/pages/apis/electronic-seal-api/seal-api-stepper.md
- src/pages/apis/pdf-extract/extract-stepper.md
- src/pages/apis/pdf-services/start-modifying-pdf.md
Added the Python button to the API pages that have the get started in minutes steps
> Feature 247

- src/components/form-data-api.js
- src/pages/apis/pdf-services.md
- src/pages/pricing/contact/sales/form-data-api/form-data-api-content.md
> Form Data API

- src/pages/apis/pdf-services/accessibility-auto-tag-api.md
- src/pages/apis/pdf-services/combine-pdf.md
- src/pages/apis/pdf-services/compress-pdf.md
- src/pages/apis/pdf-services/convert-pdf.md
- src/pages/apis/pdf-services/create-pdf.md
- src/pages/apis/pdf-services/delete-pdf-pages.md
- src/pages/apis/pdf-services/document-generation.md
- src/pages/apis/pdf-services/e-seal.md
- src/pages/apis/pdf-services/extract-pdf-content.md
- src/pages/apis/pdf-services/get-pdf-properties.md
- src/pages/apis/pdf-services/html-to-pdf.md
- src/pages/apis/pdf-services/linearize-pdf.md
- src/pages/apis/pdf-services/ocr-pdf.md
- src/pages/apis/pdf-services/remove-pdf-password.md
- src/pages/apis/pdf-services/reorder-pdf-pages.md
- src/pages/apis/pdf-services/replace-pdf-pages.md
- src/pages/apis/pdf-services/rotate-pdf-pages.md
- src/pages/apis/pdf-services/secure-pdf.md
- src/pages/apis/pdf-services/split-pdf.md
- src/pages/home/accessbility-auto-tag.md
- src/pages/home/create-pdf-from-url.md
- src/pages/home/dynamic-pdf-document-generation.md
- src/pages/home/e-seal.md
- src/pages/home/pdf-content-structure.md
> --Updated .NET code

- gatsby-browser.js
- src/components/auto-redact.js
- src/components/pdfAccessibility.js
- src/components/salesContactUs.js
- src/components/tech-supportContactUs.js
- src/pages/home/home-storyies.md
- src/pages/pricing/contact/sales/auto-redact/auto-redact-content.md
- src/pages/pricing/contact/sales/auto-redact/index.md
> Release aug 16

- src/pages/apis/pdf-services/check-pdf-accessibility.md
> Fix : Lint issue

- src/pages/apis/pdf-services/html-to-pdf.md
> added waitTimeToLoad param in HTML to PDF

- .github/workflows/deploy.yml
- src/pages/apis/pdf-services/export-pdf-form-data.md
- src/pages/apis/pdf-services/import-pdf-form-data.md
1. Added Java code samples to documentation of two newly supported APIs in Adobe PDF Services SDK: Export PDF Form Data and Import PDF Form Data.
2. Fix for Missing download info for actions/cache@v2 
No specific open issue linked to this PR. These changes correspond to newly released SDK features (version 4.3.0) and are aligned with internal roadmap updates.
Adding these examples helps developers quickly implement these operations. Updating release notes ensures versioning information is aligned with the SDK.
npm run dev on local machine
> Adding samples for Import/Export APIs

- src/pages/apis/pdf-services/export-pdf-form-data.md
- src/pages/apis/pdf-services/import-pdf-form-data.md
With the new Release of .NET Adobe PDF Services SDK version v4.3.0. Existing samples are being updated in this PR
> Adding .NET Samples for Import/Export Form data API
